### ISSUE TITLE
why this repo?

### ISSUE THREAD

**Issue by AdrianTM** [MX-Linux/mx-exit-options#1]
Hey Jerry why not fork exit-option and edit the .conf file over there and send pull requests?

**Comment by jerry3904** [comment]
That was DO's idea after I posted to my little group that we needed to
start coming up with MXFB ideas. It's not about your conf, it's about
implementations of it for MX-23 Fluxbox.

**Comment by AdrianTM** [comment]
Will we have a different .conf for Fluxbox than for the Xfce? This tool is mostly for Fluxbox and things like i3, it's not installed by default in Xfce and not likely many people will use, plus, there's nothing in the .conf that is specific for Fluxbox, right?

**Comment by jerry3904** [comment]
All correct--seems like I erred.

We will kill the mx-exit-options and notify the MXFB user-devs to change (Melber has already forked and populated). Then perhaps create a folder such as "designs" in your exit-options repo for proposals.
